apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-jenkins
  labels:
    app: jenkins
    {{- include "jenkins.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts
        ports:
        - containerPort: {{ .Values.controller.containerPort }}
          name: http
          protocol: TCP
        - containerPort: {{ .Values.controller.containerPortM }}
          name: management
          protocol: TCP
        env:
        - name: JENKINS_OPTS
          value: "--prefix=/jenkins"
        - name: JENKINS_USER
          value: {{ .Values.controller.adminUser }}
        - name: JENKINS_PASS
          value: {{ .Values.controller.adminPassword }}
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
      volumes:
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-jenkins-pvc
