{{- if .Values.controller.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-jenkins
  labels:
    {{- include "jenkins.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.controller.ingress.ingressClassName }}
  rules:
  - host:
    http:
      paths:
      - path: /jenkins
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-jenkins
            port:
              number: {{ .Values.controller.servicePort }}
{{- end }}
